[book]
authors = ["Kyle Haefner"]
language = "en"
multilingual = false
src = "src"
title = "Learn Rust"

[output.html.playpen]
editable = true
copy-js = true
line-numbers = true  # Optional: adds line numbers for better usability